### ISSUE TITLE
The latest version cannot detect the local Ollama model.

### ISSUE THREAD

**Issue by trader108** [egoist/chatwise-releases#136]
The latest version cannot detect the local Ollama model. Is gone

**Comment by egoist** [comment]
it works for me, are you able to visit http://localhost:11434/api/tags

**Comment by trader108** [comment]
> it works for me, are you able to visit http://localhost:11434/api/tags

Now,It can be recognized on Chatkit.  But after the update of Chatwise, it cannot be recognized.

**Comment by egoist** [comment]
can you still see ollama models in the dropdown?

![Image](https://github.com/user-attachments/assets/4c89a674-e9b9-4fca-8c02-d1d7d8411ea8)

**Comment by trader108** [comment]
It's gone. However, I can use ollama on Chatkit.

**Comment by trader108** [comment]
> can you still see ollama models in the dropdown?
> 
> ![Image](https://github.com/user-attachments/assets/4c89a674-e9b9-4fca-8c02-d1d7d8411ea8)

It's gone. However, I can use ollama on Chatkit.

**Comment by Marcisbee** [comment]
Same issue for me!

Just clicked update to latest version and ollama no longer works.

![Image](https://github.com/user-attachments/assets/bf41544b-bcee-4aa3-ab6d-598a9a1b68ec)

In models list all of the ollama things are gone now.

Also checked that api works `/api/tags` returns 200 with all of the models

**Comment by Marcisbee** [comment]
I use 0 proxies in my setup. Raw ollama server with 0.0.0.0 host on local PC. It worked befor the update and now it doesnt. I can still connect via ollama api, but not with chatwize

**Comment by trader108** [comment]
My issue was resolved by turning off the proxy, and I'm sorry, I can't help
you with this problem either.

Marcis Bergmanis ***@***.***> 于2025年2月11日周二 00:15写道：

**Comment by egoist** [comment]
> I use 0 proxies in my setup. Raw ollama server with 0.0.0.0 host on local PC. It worked befor the update and now it doesnt. I can still connect via ollama api, but not with chatwize

weird, it’s working for me, on windows it also doesn’t use any proxy, can you try latest v0.6.64 and see if it works

**Comment by Marcisbee** [comment]
Still doesnt work. Could be that macos update was at fault? I did get macos update to latest over the weekend.

**Comment by trader108** [comment]
[image: image.png]
Yes, it can be used normally.

EGOIST ***@***.***> 于2025年2月11日周二 00:27写道：

**Comment by Alsan** [comment]
> My issue was resolved by turning off the proxy, and I'm sorry, I can't help
> you with this problem either.
> 
> Marcis Bergmanis ***@***.***> 于2025年2月11日周二 00:15写道：
> […](#)

The proxy functionality is now working correctly. However, I still require a proxy for internet searches. The older version performed excellently when connecting to the local model, without being affected by proxy settings – which is why I subscribed to the Pro version.
